### ISSUE TITLE
There is an error in the Wiki link and a 404 page is displayed.

### ISSUE THREAD

**Issue by koba-ninkigumi** [ghiscoding/slickgrid-universal#1140]
### Describe the bug

The Step by Step link for React on the Wiki page is incorrect, clicking on it will bring up a 404 page.

https://github.com/ghiscoding/slickgrid-universal/wiki

```
- React [Wiki - HOWTO (Step by Step)](https://github.com/ghiscoding/slickgrid=react/wiki/HOWTO--Step-by-Step)
+ React [Wiki - HOWTO (Step by Step)](https://github.com/ghiscoding/slickgrid-react/wiki/HOWTO--Step-by-Step)
```

The "=" should be changed to "-".

### Reproduction

The Step by Step link for React on the Wiki page is incorrect, clicking on it will bring up a 404 page.

https://github.com/ghiscoding/slickgrid-universal/wiki

### Which Framework are you using?

React

### Environment Info

```shell
*
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/slickgrid-universal/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [Wikis](https://github.com/ghiscoding/slickgrid-universal/wiki).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/slickgrid-universal/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/slickgrid-universal/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
Ah you're right thanks for that, I just fixed it now. Thanks for using the lib 😃
