### ISSUE TITLE
Mouse multi cell selection does not work with active editor

### ISSUE THREAD

**Issue by zewa666** [ghiscoding/slickgrid-universal#1380]
### Describe the bug

As we recently found out in Example19, while an Editor is open we cant select multiple cells with the mouse. it works with the keyboard shift + arrow navigation though.

I guess its the editor stealing the focus but I'll investigate and provide a PR

### Reproduction

* example19
* activate editor in a cell
* try selecting it plus a few neighbors using the mouse

### Which Framework are you using?

Vanilla / Plain JS

### Environment Info

```shell
| Executable          | Version |
| ------------------- | ------- |
| (framework used)    | VERSION |
| Slickgrid-Universal | latest |
| TypeScript          | VERSION |
| Browser(s)          | VERSION |
| System OS           | VERSION |
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/slickgrid-universal/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [Wikis](https://github.com/ghiscoding/slickgrid-universal/wiki).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/slickgrid-universal/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/slickgrid-universal/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zewa666** [comment]
So I found the two places that cause the issue

```diff
diff --git a/packages/common/src/extensions/slickCellRangeSelector.ts b/packages/common/src/extensions/slickCellRangeSelector.ts
index 9e0d0cb8..632adb7e 100644
--- a/packages/common/src/extensions/slickCellRangeSelector.ts
+++ b/packages/common/src/extensions/slickCellRangeSelector.ts
@@ -347,10 +347,10 @@ export class SlickCellRangeSelector {

     // prevent the grid from cancelling drag'n'drop by default
     // unless an editor is open if so keep bubbling the event to avoid breaking editor inputs focusing/selecting
-    if (!this._grid.getEditorLock().isActive()) {
+    // if (!this._grid.getEditorLock().isActive()) {
       e.stopImmediatePropagation();
       e.preventDefault();
-    }
+    // }
   }

   protected handleDragStart(e: SlickEventData, dd: DragRowMove) {
diff --git a/packages/common/src/extensions/slickCellSelectionModel.ts b/packages/common/src/extensions/slickCellSelectionModel.ts
index 51e62f47..5a22f81e 100644
--- a/packages/common/src/extensions/slickCellSelectionModel.ts
+++ b/packages/common/src/extensions/slickCellSelectionModel.ts
@@ -163,10 +163,11 @@ export class SlickCellSelectionModel implements SelectionModel {
   }

   protected handleBeforeCellRangeSelected(e: SlickEventData): boolean | void {
-    if (this._grid.getEditorLock().isActive()) {
-      e.stopPropagation();
-      return false;
-    }
+    // if (this._grid.getEditorLock().isActive()) {
+    //   e.stopPropagation();
+    //   return false;
+    // }
+    return true;
   }

   protected handleCellRangeSelected(_e: SlickEventData, args: { range: SlickRange; }) {

```

The first change got introduced a few months back in [this PR](https://github.com/ghiscoding/slickgrid-universal/pull/1183).
With my reverted changes that's how it behaves for me. Notice how if you single click once inside the editor, the selection works again. So actually no difference.
![selection_editor](https://github.com/ghiscoding/slickgrid-universal/assets/2861414/a459443e-cdfb-4153-8898-6dc17276e3c5)

But cell selection now works properly, even with the editor and having the second change (see patch above)
![fixed_selection](https://github.com/ghiscoding/slickgrid-universal/assets/2861414/12b71394-c3b0-4008-8800-ed6d0d607c39)

**Comment by ghiscoding** [comment]
hmm the fix I've done in PR #1183 was about the editor that stopped working as displayed in the PR, does your change break that again or...? I mean you should be able to change the cursor anywhere within the input editor and still be able to type some text (that is what the PR 1183 fixed), I want to make sure that we are not reintroducing that regression

**Comment by zewa666** [comment]
i think the mentioned PR took a shortcut by saying as soon as a editor is open (anywhere) do something.by doing so it introduced the current bug. instead, i think, the correct approach would have been to check whether the mouse is at that time within the boundaries of the input.

I'll have to properly recheck the two mentioned examples by you and see to implement the original workaround in the described manner while not messing up the selection feature.

**Comment by ghiscoding** [comment]
I'm the shortcut guy then hahah, if you find a better way to doesn't regress then I'm all for it :)

**Comment by zewa666** [comment]
hehe not meant as a complaint, just wanted to make sure to get the original intention right.

**Comment by ghiscoding** [comment]
side note, I finally found how to fix the VSCode debugger to work with all the packages **and** the Vite Example package, previously the Vite portion wasn't working now it finally breaks everywhere. It just took couple years for me to fix it 😝 

This might be helpful to troubleshoot current issue, maybe, hopefully ;)

here's the commit fb67d22b that fixes it

![image](https://github.com/ghiscoding/slickgrid-universal/assets/643976/fa1835d2-52c1-4b83-a259-5da850587631)


![image](https://github.com/ghiscoding/slickgrid-universal/assets/643976/de3e98cd-1e65-49ba-bfc9-f9d68788b43b)
