### ISSUE TITLE
AutoResize option with "resizeDetecion : 'container'" invoke the "[ResizeObserver is not a constructor]" exception.

### ISSUE THREAD

**Issue by good-ghost** [ghiscoding/slickgrid-universal#1480]
### Describe the bug

In the Salesforce LWC,

AutoResize option with "resizeDetecion : 'container'" invoke the "[ResizeObserver is not a constructor]" exception.

### Reproduction

Create the LWC component from Salesforce platform.

Here is code I used.
``` javascript
		const container = this.template.querySelector(".user-grid");
		
		let gridOptions = {
			enableAutoResize: true,
			autoResize: {
				container: container,
				resizeDetection: 'container',  // the 2 options would be 'container' | 'window'
    			// calculateAvailableSizeBy: 'container',
			},
			...
		];
```

Above code create the exception with message "[ResizeObserver is not a constructor]".

How can I handle this? Anyone had sole this problem?

### Which Framework are you using?

Other

### Environment Info

```shell
| Executable          | Version |
| ------------------- | ------- |
| Salesforce LWC      | 60.0    |
| Slickgrid-Universal | 4.6.1   |
| TypeScript          | -       |
| Browser(s)          | Chrome 124 |
| System OS           | Windows 10 |
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/slickgrid-universal/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [Wikis](https://github.com/ghiscoding/slickgrid-universal/wiki).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/slickgrid-universal/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/slickgrid-universal/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
That code is part of the Example 14 demo and it works fine, it must be another one of those "Doesn't work in Salesforce" problem and if that is the case then there's nothing I can do. 

https://github.com/ghiscoding/slickgrid-universal/blob/094d7602d7170b2f395985ce5635041bb2b803d2/examples/vite-demo-vanilla-bundle/src/examples/example14.ts#L411-L415

The resize detection `container` uses the [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) and I assume it's block, like many other things, on Salesforce. That code was added but someone else, I would suggest you use the regular resizer

**Comment by good-ghost** [comment]
OK, Thanks,

I will try with regular resizer.
