### ISSUE TITLE
Quotes newlines/tabs excelcopybuffer

### ISSUE THREAD

**Issue by zewa666** [ghiscoding/slickgrid-universal#1559]
### Describe the bug

With the ExcelCopyBuffer I'd expect if a paste text is quoted with doublequotes, newlines within that text shouldn't break to new cells. Also when tabs are contained, the text after them is cut off.

I just wanted to check back with you whether you @ghiscoding  too think this is a wrong behavior. If so, I'll create a PR to fix that.

### Reproduction

* Go to example 19 (https://ghiscoding.github.io/slickgrid-universal/#/example19)
* Copy the following text into your editor of choice and replace \n with real newlines and \t with a tab key
```text
"this is\n
a \t newline\n
test"
```
* Check the result

### Which Framework are you using?

Angular

### Environment Info

```shell
| Executable          | Version |
| ------------------- | ------- |
| (framework used)    | Angular |
| Slickgrid-Universal | latest |
| TypeScript          | VERSION |
| Browser(s)          | VERSION |
| System OS           | VERSION |
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/slickgrid-universal/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [Wikis](https://github.com/ghiscoding/slickgrid-universal/wiki).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/slickgrid-universal/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/slickgrid-universal/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
that seems valid indeed
