### ISSUE TITLE
Date Filter does not always change picker value and also has DOM leakages 

### ISSUE THREAD

**Issue by ghiscoding** [ghiscoding/slickgrid-universal#1582]
### Describe the bug

I was troubleshooting what I thought was a styling issue with the Compound Date Filter which happened after changing the filters dynamically (via Example 10 or 11), the input seem to be wider than the available container. It turns out that it's a much bigger bug in the external lib which is even creating leakage. 

### Reproduction

After investigating, I found out that the new vanilla-calendar is overriding the input as the new calendar picker and when we then click the same input, it also creates a 2nd date picker. I also found that after clearing the filter and updating filter dynamically, it did not always set the new date into the picker and that is because the set filter value was missing the `cv.update({ year: true, month: true }}`, but then after doing this `.update()`, that is when the leakage happens (which overrides the input and creates 2 picker elements after clicking the input)

what the animated gif is demoing
1. after clearing/updating dynamically the filter, the input becomes wider than the available space
2. the input gets overriden and becomes the new picker
3. clearing, then setting new filter, doesn't correctly set the dates
4. doing a `query.selectorAll` in the console, shows 2 elements with the CSS class `.vanilla-calendar` but there should be only 1 element

![brave_7ZNVAcHMMA](https://github.com/ghiscoding/slickgrid-universal/assets/643976/b78b4085-a971-45b6-b7e5-e033456d703d)

### Which Framework are you using?

Vanilla / Plain JS

### Environment Info

```shell
| Executable          | Version |
| ------------------- | ------- |
| (framework used)    | all |
| Slickgrid-Universal | latest |
| TypeScript          | latest |
| Browser(s)          | all |
| System OS           | Windows |
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/slickgrid-universal/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [Wikis](https://github.com/ghiscoding/slickgrid-universal/wiki).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/slickgrid-universal/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/slickgrid-universal/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
@zewa666 FYI, this is a bug in the external vanilla-calendar picker, which at this point I'm still using my fork of it, so I'll look at fixing it in my fork. One I have in mind to fix this issue is to explicitly initialize the calendar picker **before** calling the `vs.update()`. I have also opened a bug on the original repo, we'll see if the author replies and provides a better fix

**Comment by zewa666** [comment]
I'm going to be on vacation a couple of days but will take a look at the PR whichever one it is than.

**Comment by ghiscoding** [comment]
it's all good, I just wanted to inform you that's all, I'll take care of it all.

**Comment by ghiscoding** [comment]
and there you go, here's the [PR](https://github.com/ghiscoding/vanilla-calendar-picker/pull/5) in my fork that fixes the issue
