### ISSUE TITLE
custom HTMLElement inside header loses event handler

### ISSUE THREAD

**Issue by ghiscoding** [ghiscoding/slickgrid-universal#1605]
### Describe the bug

This bug was first reported in Angular-Slickgrid but is really code related to Slickgrid-Universal, so I'm closing the Angular-Slickgrid issue and opening this new one with same info

> When I use a custom HTMLElement inside the name property of a column definition like this
> 
> ```
>   const div = document.createElement('div');
>   const button = document.createElement('button');
>   button.textContent = 'click';
>   div.appendChild(button);
>   button.addEventListener('click', () => alert('hi'));
> 
>     this.columnDefinitions = [
>       { id: 'title', name: div, field: 'title' },
> ```
> 
> In angular slickgrid the click event handler does not trigger whereas if I do the same in a normal slickgrid (6pac repo) grid the click event is fired.

### Reproduction

> https://stackblitz.com/edit/stackblitz-starters-akwtsl?file=src%2Fslickgrid-angular%2Fslickgrid-angular.component.html
> 

### Which Framework are you using?

Angular

### Environment Info

```shell
| Executable          | Version |
| ------------------- | ------- |
| Angular-Slickgrid   | 8.3.1 |
| Slickgrid-Universal | 5.3.2 |
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/slickgrid-universal/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [Wikis](https://github.com/ghiscoding/slickgrid-universal/wiki).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/slickgrid-universal/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/slickgrid-universal/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
This is a regression caused by PR #1476 which was fixing another bug #1475 

in PR #1476, I used `cloneNode(true)` to clone the HTML element but that method doesn't copy the event listeners. This change does not exist in SlickGrid, hence why the new bug doesn't show up in SlickGrid.

At this point, I'm not sure if the use of `cloneNode()` is the best approach and if not, then what approach should we use to not regress #1475. Note that the button listener does work after removing the `cloneNode()` but reopens my previous fix for #1475 

@zewa666 @ardakod I'm opened to suggestion here

**Comment by zewa666** [comment]
well the root-cause is understandable.

1. First time around you create the span element for the title. Its not yet attached to the DOM so `appendChild` will do so
2. When the picker menu is constructed it tries to assemble the name via `pickerHeaderColumnValueExtractor` from global-grid-options.ts. In here there is an issue tough ... it grabs the name by supposing it's a string, yet it is the in step1 created span element.  Next it calls `applyHtmlCode` which will in the original appendChild, thus move the element from the column header to the picker.
3. Next time rendering the columnheaders due to column toggling, the same referenced DOM Element will be moved from the picker to the columnHeader, leaving the empty place

so the issue I'd say is how the label for the picker is constructed. I've created a PR with a potential solution.

**Comment by ghiscoding** [comment]
yeah I found that if I modify the global value extractor as below, it fixes the issue without the need for the clone. I'm not sure reading the `.textContent` is always the right way to do it though

```ts
function pickerHeaderColumnValueExtractor(column: Column, gridOptions?: GridOption) {
  let colName = column?.name ?? '';
  if (colName instanceof HTMLElement) {
    colName = colName.textContent || '';
  }
  const headerGroup = column?.columnGroup || '';
  const columnGroupSeparator = gridOptions?.columnGroupSeparator ?? ' - ';
  if (headerGroup) {
    return headerGroup + columnGroupSeparator + colName;
  }
  return colName;
}
```

**Comment by zewa666** [comment]
yeah it was just a quick one to show where the potential solution could go. Seeing you did the same makes me feel like its the proper thing to do. I've closed my PR since you're at it anyways.

if you don't like textContent you could instead use the deepClone here since you'll most likely not care about the attached handlers in the context of the columnPicker. I'd personally stick with the textContent as it feels *cleaner* though

**Comment by ghiscoding** [comment]
yeah the concern I have is the following (I've also put the same comment in your now closed PR)

I had another possible problem with the `.textContent`, this will read all element texts but is that really ideal though? I mean I just tested this with an HTML element that has some text and a button with text and it gives me what is shown below (the button text is also pulled). However, I'm not sure that we can do much about it?!?

![image](https://github.com/user-attachments/assets/91d834e1-ed82-4017-a39a-7128d6720789)

that is using the following code

```ts
const div = document.createElement('div');
    const button = document.createElement('button');
    button.className = 'button button-small';
    button.textContent = 'click';
    button.addEventListener('click', () => alert('hi'));
    div.appendChild(document.createTextNode('Column 1 '));
    div.appendChild(button);

    this.columnDefinitions = [
      {
        id: 'sel', name: div, field: 'num', width: 80, type: FieldType.number,
        excludeFromExport: true,
        resizable: true,
        filterable: true,
        selectable: false,
        focusable: false
      },
```

**Comment by zewa666** [comment]
well if you'd want to maintain that functionality here too, which I quite frankly think is a sideeffect users typically dont think off, we'd need a deepClone of the element for the picker.

I think the better approach alltogether would be to introduce something like a `pickerLabel: string | HTMLElement | DocumentFragment` property on the column interface which would be taken first and textContent of name as a fallback.

**Comment by ghiscoding** [comment]
https://github.com/ghiscoding/slickgrid-universal/blob/b1d42f539b4e1f501e9652d8c2bcd27f29ea700a/packages/common/src/extensions/slickColumnPicker.ts#L49-L50

so do you mean something like this instead

```ts
headerColumnValueExtractor: (columnDef: Column) => getHtmlStringOutput(columnDef.pickerLabel || columnDef.name || '', 'innerHTML')
```

**Comment by zewa666** [comment]
yep exactly, that would keep textContent as default, which most likely will be fine 9 out of 10 times. but for these other cases you can create the label to override the behavior

**Comment by ghiscoding** [comment]
ok so I've opened PR #1607, I'm just missing a bit more unit tests and E2E tests but apart from that the code should be good as it is and fix this issue without regressing. @zewa666 thanks a ton for the feedback provided, it was again very helpful 😉
