### ISSUE TITLE
Issue with enableExcelCopyBuffer and Hidden Columns Causing Selection Offset

### ISSUE THREAD

**Issue by hwlv** [ghiscoding/slickgrid-universal#1634]
### Describe the bug

When using the enableExcelCopyBuffer option set to true in slickgrid-universal, I’ve encountered an issue where selecting a range of cells causes the selection area to be offset if there is a hidden column in the grid. It appears that the hidden column is being included in the calculations, leading to discrepancies between the mouse position and the selected cells.

### Reproduction

1. Set enableExcelCopyBuffer to true.
2. Add a column with the hidden property set to true.
3. Attempt to select a range of cells that includes both visible and hidden columns.

<img width="1116" alt="image" src="https://github.com/user-attachments/assets/6028d4d6-e6a7-438a-bfb8-4b22f4f0a24a">

### Which Framework are you using?

React

### Environment Info

```shell
| Executable          | Version |
| ------------------- | ------- |
| (framework used)    | VERSION |
| Slickgrid-Universal | VERSION |
| TypeScript          | VERSION |
| Browser(s)          | VERSION |
| System OS           | VERSION |
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/slickgrid-universal/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [Wikis](https://github.com/ghiscoding/slickgrid-universal/wiki).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/slickgrid-universal/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/slickgrid-universal/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
cc @zewa666

**Comment by ghiscoding** [comment]
The `hidden` column property was something that was added not that long ago in the `6pac/slickgrid` project but it is not not fully supported. The Grid Presets is much more supported to hide columns
