### ISSUE TITLE
Reducing time complexity

### ISSUE THREAD

**Issue by Vsinghal339-source** [ghiscoding/slickgrid-universal#1668]
### Describe the bug

We found that the due to the below code, the time complexity is O(n square) which can be reduced to O(n)

Modified code:
```
 DataView.getAllSelectedFilteredItems = function () {
      /* istanbul ignore if */
      if (!Array.isArray(this.selectedRowIds)) {
        return [];
      }

      const selectedRowIdSet = new Set(this.selectedRowIds); // Add new set 
      const intersection = this.filteredItems.filter((a) => selectedRowIdSet.has(a[this.idProperty]));
      return (intersection || []);
    }
```

### Reproduction

For large data set, the page hange for 1 minute

### Which Framework are you using?

React

### Environment Info

```shell
| Executable          | Version |
| ------------------- | ------- |
| (framework used)    | VERSION |
| Slickgrid-Universal | VERSION |
| TypeScript          | VERSION |
| Browser(s)          | VERSION |
| System OS           | VERSION |
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/slickgrid-universal/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [Wikis](https://github.com/ghiscoding/slickgrid-universal/wiki).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/slickgrid-universal/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/slickgrid-universal/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Vsinghal339-source** [comment]
@ghiscoding Please do check this

**Comment by ghiscoding** [comment]
That's a good suggestion, and I would like if you could contribute directly to the project and become a contributor to the project. Would you like to contribute? If you need help on how to contribute then let me know

**Comment by Vsinghal339-source** [comment]
@ghiscoding Yes please add me as a contributor. THanks

**Comment by Vsinghal339-source** [comment]
@ghiscoding Please review the PR https://github.com/ghiscoding/slickgrid-universal/pull/1670
