### ISSUE TITLE
Grouping Performance Issue

### ISSUE THREAD

**Issue by Vsinghal339-source** [ghiscoding/slickgrid-universal#1678]
### Describe the bug

Requirement: Approximately 60,000 records are available.

The code took about four to five seconds to finish when we used the grouping feature and any of its functions, such as expand all, collapse all, add grouping, and remove grouping. After conducting preliminary investigation, we discovered that the line below was consuming all of the time during the refresh function in the slickDataView.ts file. However, we can't pinpoint the precise underlying reason. Please assist in locating the problematic code.

`this.onRowsChanged.notify({ rows: diff, itemCount: this.items.length, dataView: this, calledOnRowCountChanged: (countBefore !== this.rows.length) }, null, this);`

### Reproduction

this.onRowsChanged.notify({ rows: diff, itemCount: this.items.length, dataView: this, calledOnRowCountChanged: (countBefore !== this.rows.length) }, null, this);

### Which Framework are you using?

Vanilla / Plain JS

### Environment Info

```shell
| Executable          | Version |
| ------------------- | ------- |
| (framework used)    | VERSION |
| Slickgrid-Universal | VERSION |
| TypeScript          | VERSION |
| Browser(s)          | VERSION |
| System OS           | VERSION |
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/slickgrid-universal/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [Wikis](https://github.com/ghiscoding/slickgrid-universal/wiki).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/slickgrid-universal/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/slickgrid-universal/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Vsinghal339-source** [comment]
@ghiscoding Please check this

**Comment by ghiscoding** [comment]
I don't really know but I would say, do a global search for the event name and start commenting code that you find. There's potentially this code below, but it was put in place for the reason described in the code

https://github.com/ghiscoding/slickgrid-universal/blob/8d7683cd5a9409546c211a93ee5f3a12ac34e264/packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts#L834-L843

**Comment by ghiscoding** [comment]
Yeah so after testing that a bit on [Example 3](https://ghiscoding.github.io/slickgrid-universal/#/example03) which has a button to add 500K items. I added some perf logs and we might improve the code has sown below to improve perf but I don't see that much of a difference with 500K.

```ts
this._eventHandler.subscribe(dataView.onRowsChanged, (_e, args) => {
  if (Array.isArray(args?.rows)) {
    console.time('Rows Changed Perf');
    const ranges = this.slickGrid!.getRenderedRange();
    args.rows.forEach((row: number) => {
      if (row >= ranges.top && row <= ranges.bottom) {
        grid.updateRow(row);
      }
    });
    grid.render();
    console.timeEnd('Rows Changed Perf');
  }
});
```

here's the result of the console time perfs, we can see it's a bit better with condition check but it's not a huge difference. On the Example 3 with 500K, I only see a 1-2sec wait when grouping so it's not what you see on your side but that could vary depending on your data.

```sh
# old code
Rows Changed Perf: 31.5830078125 ms
Rows Changed Perf: 30.7841796875 ms
Rows Changed Perf: 30.51513671875 ms

# new code with rendered range check
Rows Changed Perf: 23.989013671875 ms
Rows Changed Perf: 25.4140625 ms
Rows Changed Perf: 28.677978515625 ms
```

The steps that I used was to use [Example 3](https://ghiscoding.github.io/slickgrid-universal/#/example03) then
1. click on "500K" button to add more items
2. scroll to the middle of the grid
3. use any of the group buttons (but always use the same one for testing)

Even if I don't see much of a difference, I think we can still push this code change. I'll let you test it out and improve it if you can. If that is not helping then like I said above, just do a global search for `onRowsChanged` and try commenting other piece of code to find which subscription causes the delay but I really think it's this one here.

**Comment by ghiscoding** [comment]
So I went ahead and opened a PR #1680, I believe that will fix the slowness you detected and even if doesn't it's still a good code change to do

**Comment by Vsinghal339-source** [comment]
Yes this PR seems good for some performances
