### ISSUE TITLE
is this released?

### ISSUE THREAD

**Issue by tisys-erp** [ghiscoding/slickgrid-universal#22]
hello, can the universal project already be used in production?

**Comment by ghiscoding** [comment]
It's not on NPM yet, I'll release a final version in a week or two, once I completed certain things.

**Comment by ghiscoding** [comment]
Just as a curiosity, are you looking at using this with vanilla TypeScript, Salesforce or any other Frameworks?

**Comment by ghiscoding** [comment]
@tisys-erp 
It's now published under the new `@slickgrid-universal` org that I had to create for it to work. 
See the version `0.1.0` under [@slickgrid-universal](https://www.npmjs.com/org/slickgrid-universal) on NPM

This is the first time I publish under an org, it seems fine but if there's any problem then please let me know
