### ISSUE TITLE
Use the excel-export package in the slickgrid-vanilla-bundle version?

### ISSUE THREAD

**Issue by mcallegario** [ghiscoding/slickgrid-universal#409]
Hi!
Sorry for my lack of knowledge, but how do I use the excel-export package in the slickgrid-vanilla-bundle version?

From now on, I thank you for the excellent work.

**Comment by ghiscoding** [comment]
It's in the package [README](https://github.com/ghiscoding/slickgrid-universal/tree/master/packages/excel-export) and in the [Wiki](https://github.com/ghiscoding/slickgrid-universal/wiki/Export-to-Excel) and in an [Example](https://github.com/ghiscoding/slickgrid-universal/blob/master/examples/webpack-demo-vanilla-bundle/src/examples/example03.ts), that should be enough to look into

**Comment by ghiscoding** [comment]
closing since I believe the question was answered

**Comment by mcallegario** [comment]
dear Ghislain,

Thank you very much for your attention, I use slickgrid-universal on Sharepoint so I make reference to "slickgrid-vanilla-bundle.js", this is my difficulty, as I don't have much knowledge to transform the excel-Export package to the " vanilla-bundle"... within my limitations I tried to generate the bundle, but I wasn't successful I always stop at the error:

![image](https://user-images.githubusercontent.com/44271732/125960730-ce2b66d5-e5f4-4063-8113-9bfaa5b04253.png)

Please would it be possible for you to help me once again with tips? How to generate the package correctly or helping me with the error.

Graciously,
Marcos Callegario

**Comment by ghiscoding** [comment]
That's a WebPack 5 error and if you read carefully it says that "stream", node "core" and some more used to have included polyfill in WebPack 4 but they removed that in WebPack 5 and that caused a lot of users problem and complaining about it. If you search over the net, you can find this SO [How to Polyfill node core modules in webpack 5](https://stackoverflow.com/questions/64557638/how-to-polyfill-node-core-modules-in-webpack-5) or this GitHub [issue](https://github.com/angular/angular-cli/issues/20819)

in my case, I just disable the warning and won't have the polyfill (so it won't work on old browser like IE but I don't care), just look at the `fallback` section in your `webpack.config.js` 
https://github.com/ghiscoding/slickgrid-universal/blob/e703789282a4eb45428f4516c74dba20ebe720b2/examples/webpack-demo-vanilla-bundle/webpack.config.js#L41-L52

If you do want to add the polyfill to still support the old browser, I think you can add this to your `tsconfig.json`
```json
{
  ...
  "compilerOptions": {
    "paths": {
      "stream": [ "./node_modules/stream-browserify" ]
    },
}
```

So anyway, this is a WebPack issue, it's not related to the library.

**Comment by mcallegario** [comment]
Great... worked perfectly....
Thank you so much!!!
Once again, congratulations for the excellent work.

**Comment by ghiscoding** [comment]
another happy user, you can also upvote if you like the lib 😉 ⭐
