### ISSUE TITLE
Bug in onCellClick event when using treegrid

### ISSUE THREAD

**Issue by mcallegario** [ghiscoding/slickgrid-universal#562]
### Your Environment

| Software               | Version(s) |
| --------------------- | ---------- |
| Slickgrid-Universal  | x.y        |
| TypeScript               | x.y        |
| Package Name        | x.y        |

### Describe the Bug

I'm displaying a cell phone that contains a tag of an SVG icon with a class attribute in a treegrid, when clicking on the icon, the following error occurs:
![image](https://user-images.githubusercontent.com/44271732/143624915-b12015c8-0ec7-470e-a543-ab50f387a5a4.png)

### Possible Solution

I fixed the problem by making these tweaks to the code, as I'm still not able to use the latest version, because of XSS, I couldn't make the patch branch.
Hope this little fix can help you.
![image](https://user-images.githubusercontent.com/44271732/143625337-926bde43-4bdd-4c7d-ad6a-ab84190a3f96.png)

**Comment by ghiscoding** [comment]
it would be great to get a PR with the fix
I would however keep the optional chaining on it to be on safe side, so more like this
`if (typeof targetElm?.className === 'string') {`

Note however that I already started merging code for the next upcoming 1.0.0 release so there are small breaking change (mostly in styling for now)
