### ISSUE TITLE
partial translation with custom i18n namespase

### ISSUE THREAD

**Issue by someusersomeuser** [ghiscoding/slickgrid-universal#738]
### Describe the bug

with custom namespace some items in menu not translated - duplicate namespace in key string

@slickgrid-universal\common\dist\esm\extensions\extensionUtility.js -> translateMenuItemsFromTitleKey(items)

this method add translationPrefix to item.titleKey before translate, but titleKey already contains translationPrefix:

@slickgrid-universal\common\dist\esm\extensions\slickGridMenu.js -> addGridMenuCustomCommands(originalCommandItems)

fix translateMenuItemsFromTitleKey to remove duplicate translationPrefix, or check, that the titleKey not already starts with translationPrefix 

### Reproduction

1. set gridOptions.translationNamespace = 'aurelia-slickgrid'
2. load i18n translations for grid to this namespace

### Environment Info

```shell
aurelia 1
@slickgrid-universal/common@1.3.7
typescript none
browsers any
os any
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/slickgrid-universal/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [Wikis](https://github.com/ghiscoding/slickgrid-universal/wiki).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/slickgrid-universal/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/slickgrid-universal/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
Pull Request are welcome if you think that you have a fix. I never used the prefix so I'm not the best person to look into this

**Comment by someusersomeuser** [comment]
simple way is check that translationPrefix already contains

but imho true way remove prefix from all *Menu sources, and save it in translateMenuItemsFromTitleKey.

what is your opinion?

**Comment by ghiscoding** [comment]
hmm I`m not sure that adding string check of the prefix for every single translation key is necessary a good thing. I would rather fix the source of the duplicate prefix. The thing is that as I said I never used it myself and the person who opened this [issue](https://github.com/ghiscoding/aurelia-slickgrid/issues/338) in Aurelia-Slickgrid, which I've added the feature for him, never came back to me to confirm if it works as expected. So I'm not necessarily surprised about this new issue you opened, So I still think fixing the source is ideal

**Comment by someusersomeuser** [comment]
I checked the code history. I think previously it worked as expected.
this commit adds duplicate prefix [https://github.com/ghiscoding/slickgrid-universal/commit/aeba4801fdb5cba3976984f5c591be8c1ad97e4b](feat(plugins): move external Header Menu into Slickgrid-Universal)

my new idea - simply remove prefix from translateMenuItemsFromTitleKey

then internal keys still contains prefix, if it is set
and for custom menu items, user can add another namespace if needed, or use default namespace, or set the same prefix manually
